### ISSUE TITLE
JSON-файл не можливо завантажити у  БД (edata.sqlite)

### ISSUE THREAD

**Issue by OldBlindTiger** [ap-Codkelden/edata#3]
Робилось під Win 7
1. **edata.py** був сформований **e-data_osvita_out.json**
    `python.exe edata.py -p 02124781 04544501 -j -s 14.09.2015 -e 30.06.2016`
2. **json2sqlite.py** неможливо завантажити **e-data_osvita_out.json** у БД **edata.sqlite**
    `python.exe json2sqlite.py -f e-data_osvita_out.json`
3. Видає помилку:
```
Traceback (most recent call last):
  File "json2sqlite.py", line 220, in <module>
    main()
  File "json2sqlite.py", line 216, in main
    edb.import_file(f)
  File "json2sqlite.py", line 171, in import_file
    json_data = json.load(f)
  File "C:\Users\PETER\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "C:\Users\PETER\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 706: character maps to <undefined>
```
4. **e-data_osvita_out.json** додається
[e-data_osvita_out.json.zip](https://github.com/ap-Codkelden/edata/files/575414/e-data_osvita_out.json.zip)

**Comment by OldBlindTiger** [comment]
Зробів ще експерімент. 

```
python.exe edata.py -p 02124781 04544501 -j -s 14.09.2015 -e 16.09.2015

python.exe json2sqlite.py
```

не завантажує **json**.

На мою думку з ключем **-p**, некоректно формується **json**

**Comment by ap-Codkelden** [comment]
@OldBlindTiger , перше пофіксив. Як і думав, це віндові юнікодопроблеми. 

Щодо другого: файлу с JSON не залишилося? Бо там API вони поламамли, вивантажити не можу.

**Comment by OldBlindTiger** [comment]
Дякую, все працює !

Другий приклад, це додатковий приклад.
