### ISSUE TITLE
Відображення у консолі кількості оброблених записів 

### ISSUE THREAD

**Issue by OldBlindTiger** [ap-Codkelden/edata#4]
Побажання.

У скриптах **edata.py** та **json2sqlite.py** додати можливість виводу у консоль кількості сформованих або оброблених записів.

**Comment by ap-Codkelden** [comment]
@OldBlindTiger  JSON просто не записується на диск, якщо обрано у SQLite, а так він отримується. Можу зробити опцію для його залишення, якщо потрібно.
Додам щось типу:
«Додано 18 записів, усього записів: 199»

**Comment by OldBlindTiger** [comment]
> «Додано 18 записів, усього записів: 199»

**усього записів** - це те що дозволило забрати з Є-дата
**Додано 18 записів** - нові записи додані у  SQLite, при наявності контролю дублів у SQLite.

Так !

> Можу зробити опцію для його залишення, якщо потрібно.

Можна, для перевірки інформації
Можна залишити **-j**. 
Тоді коли у командному рядку є **-sql** та **-j**:
- отримана інфа додається у  **SQLite**
- додатково формується **edata.json**
